
export const ChartTypes = {
  GRADE_DIST: 'GRADE_DIST',
  HORIZONTAL_BAR_CHART: 'HORIZONTAL_BAR_CHART',
  MAP_CHART: 'MAP_CHART',
  HORIZONTAL_BAR_CHART_GROUPED: 'HORIZONTAL_BAR_CHART_GROUPED',
  HORIZONTAL_BAR_CHART_STACKED: 'HORIZONTAL_BAR_CHART_STACKED',
};
